### ISSUE TITLE
Support PostgreSQL or other open source database.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/psm#1]
Make the PSM usable with an open source database, defaulting to PostgreSQL, with no dependency on Oracle.

**Comment by cecilia-donnelly** [comment]
Initial investigation shows that substituting a PostgreSQL database for an Oracle database is likely to work with some code changes.  For initial building and deploying, it "just works."  See https://groups.google.com/forum/#!topic/psm-dev/3bS9GP0ohuw.  

Note that due (at least in part) to a change in https://github.com/OpenTechStrategies/psm/commit/3642b483df0ff611f179e4ff6825b52c7606e8fa, the application currently does not connect to the database to allow people to log in.  This is in progress -- see https://groups.google.com/d/msg/psm-dev/nzC3pP1XMFg/_IntTUOhAAAJ and that entire thread for discussion.

**Comment by cecilia-donnelly** [comment]
This turns out to be relatively straightforward.  The major database difficulties are associated with the major Hibernate version upgrade.
