### ISSUE TITLE
License Status has an apparently unused property called 'Date'

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#101]
While converting LicenseStatus to H5 I saw that it has a property called Date which does not seem to be referenced anywhere.

I made the column in seed.sql nullable and carrying on. This should be investigated and perhaps dropped.

**Comment by jasonaowen** [comment]
Oh, I missed that you opened an issue for this! Sorry about that. I noticed it while reviewing #118 and updated the PR to delete it.
