### ISSUE TITLE
OwnershipType Entity may be Obsolete

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#103]
I don't see an entry for OwnershipType in Medicade.hbm.xml and don't see any data for it in mpse_clean.sql

A quick look through the code doesn't show it ever being referenced. It is loaded as a property for Asset object, but I don't see any useful references to it from there apart from some scaffolding code:
```            
if (asset.getOwnershipType() != null) {
                String type = doLegacyMapping(asset.getOwnershipType().getCode(), XREF_OWNERSHIP_TYPE);
                sb.append(fw(type, ColumnDef.WS_000_EXT_OWN_A_BCKGRD_OWN));
```

Can we delete this class?

**Comment by jasonaowen** [comment]
At the risk of spreading FUD, let's not yet - there are relationships expressed in JSPs and in Drools rules that are not very clear to me, and are certainly not known to IntelliJ as I have it set up now. Once we understand better how those work, and can say better why `OwnershipType` existed and how it was used, then if it still makes sense then yes we should absolutely delete it - dead code is, at best, distracting.

**Comment by jasonaowen** [comment]
After looking more closely, I agree with you, @BenGalewsky - good catch! I was getting confused by [the variable of the same name in `RealProperty`](https://github.com/OpenTechStrategies/psm/blob/0987da3c32b7fca5dd606290d07464197c0072b2/psm-app/cms-business-model/src/main/resources/Entities.xsd#L1186), and references to it in [the drools validation rules](https://github.com/OpenTechStrategies/psm/blob/0987da3c32b7fca5dd606290d07464197c0072b2/psm-app/cms-business-process/src/main/resources/cms.validation.drl#L9792).

I will remove.
