### ISSUE TITLE
Broken link on Section 4 of the main page

### ISSUE THREAD

**Issue by bycheng1** [OpenTechStrategies/psm#106]
The following ext-sourcex-app link in section 4 gets you to a 404 error message:

The ext-sources-app subdirectory holds the source code to the semi-separate middleware application that provides a service wrapper around external data sources, thereby offering the PSM a consistent API to those services.

**Comment by cecilia-donnelly** [comment]
Thanks for catching this, @bycheng1!  This is because we removed the ext-sources-app subdir as discussed [on the list](https://groups.google.com/forum/#!topic/psm-dev/bOVQeUjoaB0).  I'll put in a PR to update that part of the README.
