### ISSUE TITLE
specify Linux distro preference in install instructions

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#111]
Per conversation with James just now: for now, put a nice note at the top of `INSTALL.md`, suggesting that the user will have a better time on a Debian-based Linux but that we also support RPM-based distributions.

**Comment by jasonaowen** [comment]
We have language around this! From `INSTALL.md`:

> Operating System: we recommend Debian 9 stable, also known as stretch. If you prefer Debian testing, we have had success with Debian testing (aka buster). A developer has also successfully installed the PSM on Red Hat 7.3 Enterprise Linux. If that's not feasible for your environment, any of the supported WildFly 10.1 operating systems should work, but our ability to help troubleshoot issues that come up may be limited. Once we test this on a few more platforms, we will expand the list of compatible operating systems to include other Linux distributions.
