### ISSUE TITLE
Find WebSphere and Oracle dependencies in codebase

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#12]
As part of #2, find any places where the code would need to be changed for the migrations to Wildfly and Postgres.

Ideally, make these places configurable, so that at some point in the future the platform could be changed through configuration settings.  At present, mark them for that future configurability work.

**Comment by jasonaowen** [comment]
As part of #36, we switched from Hibernate-specific entity/schema mappings to the more generic [JPA](https://en.wikipedia.org/wiki/Java_Persistence_API) annotations, which should make it easier to switch to a different persistence provider, in case a new target application server ships with such a provider (as WildFly ships with Hibernate).

We now have PostgreSQL-specific schema creation in `psm-app/db/seed.sql` and `psm-app/db/jbpm.sql`, but it should be relatively straightforward (if slightly tedious) to port that back to Oracle or to MySQL or MSSQL. Issue #254 relates to setting up a migration framework, which could also make it easier to move between databases.

Between #1, #2, and #36, I think we've found and removed any such dependencies, and addressed any incompatibilities.
