### ISSUE TITLE
investigate why JDBC installation sometimes gives "is not a valid node type name" error

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#129]
Per [conversation](https://github.com/OpenTechStrategies/psm/pull/102#discussion_r121033116) on [a change](https://github.com/OpenTechStrategies/psm/pull/102#discussion_r121519190) in #102 -- 

When Kevin was going through `INSTALL.md` and working through installing the dependencies, upon running

> $ ./bin/jboss-cli.sh --connect --command="deploy ../postgresql-{VERSION}.jar"

he got an error saying that the `.jar` file "is not a valid node type name". After #102 is merged, we'll have a workaround for this in the installation docs. But we should investigate when and why this error happens, so we can streamline the installation instructions.

**Comment by jasonaowen** [comment]
We haven't run into this again, and we haven't been able to reproduce it. We can reopen this if we do.
