### ISSUE TITLE
Review licenses of dependencies

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#147]
Check that the libraries we're using (currently in `.jar` files in this repository, soon from the Maven repo or another source) are open source and compatible with Apache 2.

**Comment by brainwane** [comment]
@cecilia-donnelly Please see https://github.com/OpenTechStrategies/psm/commit/8eaa775863252f57164975c8b1f78f44e59cd66a -- I believe this is finished (at least, double-checking the Apache artifacts you asked me to check).

**Comment by cecilia-donnelly** [comment]
Great, thanks @brainwane!  I'm going to leave the issue open for now since we have some more dependencies coming in.  Thank you for checking those libraries.  :)

**Comment by cecilia-donnelly** [comment]
We may want to use a plugin like https://plugins.gradle.org/plugin/com.github.jk1.dependency-license-report to keep track of this, once we're pulling all our dependencies from the Maven repo and updating them from there as well.

**Comment by cecilia-donnelly** [comment]
@jvasile has reviewed the licenses of our dependencies and we are in good shape. :+1:
