### ISSUE TITLE
Make Master Deployable

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#148]
# Problem
The Application requires some tables to be autocreated to be able to come up. We are able to bring it up by setting the auto create tag in the persistence.xml, bringing up the app, switching back, and then running seed.sql.

Furthermore, jBPM requires some data in the tables to work. We have some sample data from Oracle that gets past this.

This makes it hard to deploy the app to a new environment.

# Steps
- [ ] Determine the tables the autocreated tables that are required to get the app running and add create statements in seed.xml
- [ ] Determine jBPM inserts needed to get the app to run and add them to seed.xml

**Comment by jasonaowen** [comment]
I think between #182 and #190, we've completed this.
