### ISSUE TITLE
Research available workflows

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#160]
Find out what workflows are available in the application, and which ones should be available based on the documentation we have.

This first step is a broad sweep of available paths, not a deep dive into the idiosyncrasies of each specific workflow.

**Comment by brainwane** [comment]
Started in #178.

**Comment by brainwane** [comment]
According to `documentation/Requirements/CMS_-_Medicaid_Provider_Screening_Portal_-_Administrative_Features_ARS.docx`, the "logic requirements" (which map reasonably well to workflows and capabilities) are:

* Login [External]
* Logout [External]
* View Homepage
* Get Help
* Search Enrollments
* Manage My Profile
* Query Enrollment Status	
* View Enrollments
* View Enrollment Details	
* Create New Enrollment
* Edit Enrollment
* Export Enrollment Data
* Print Enrollment Data
* Initiate On-Demand Screening
* Initiate Scheduled Screening
* Approve Enrollment
* Reject Enrollment
* Manage Provider Types
* Manage Screening Schedules
* Manage Help Topics
* Manage Agreements and Addendums
* Manage Service Agents
* Search Users
* Manage Users
* Integrate With External Systems
* Send Email Notifications
* Perform Auditing
* Perform Logging
