### ISSUE TITLE
Choose first federal data source

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#17]
A few considerations when choosing the first federal data source to connect to:

__1. Which states use it?__

We know that all states must consult the Social Security Administration's Death Master File, the National Plan and Provider Enumeration System (NPPES), the List of Excluded Individuals/Entities (LEIE), the Excluded Parties List System (EPLS) (see [CFR 42](https://www.law.cornell.edu/cfr/text/42/455.436)).  I believe all states also consult [PECOS](https://pecos.cms.hhs.gov/pecos/login.do#headingLv1), but see [this GAO report](https://www.gao.gov/products/GAO-16-402) on the wide variety of databases that states and managed care plans consult when screening providers.

__2. How crucial is it to the function of the PSM?__

EPLS and PECOS both show up in many places in the codebase (245 instances of EPLS and 199 instances of PECOS), while NPPES and LEIE only appear in the documentation.  So, likely EPLS and PECOS would be preferred for this one.

__3. What steps do we need to take to use data from it?  Does it have an API or standard ETL process?__

EPLS data is available in a public extract [here](https://www.sam.gov/portal/SAM/?navigationalstate=JBPNS_rO0ABXdcACJqYXZheC5mYWNlcy5wb3J0bGV0YnJpZGdlLlNUQVRFX0lEAAAAAQApdmlldzpiOWYzY2M4Yi1hZWZmLTRkMmQtOWU0MC01YzkxZTg0MjAyNTYAB19fRU9GX18*&portal:componentId=24f38525-a064-4a77-b09f-3fa5986c2b48&interactionstate=JBPNS_rO0ABXc0ABBfanNmQnJpZGdlVmlld0lkAAAAAQATL2pzZi9uYXZpZ2F0aW9uLmpzcAAHX19FT0ZfXw**&portal:type=action##11), but there are restrictions on access: 

>Systematic access (electronic harvesting) or extraction of content from the website, including the use of "bots" or "spiders", is prohibited.

PECOS doesn't have an API yet, and at least some states still do manual lookups.  A monthly extract may be available.

**Comment by jvasile** [comment]
My chat with @brainwane reminded me I wasn't updating this issue.  So: after some discussion, @cecilia-donnelly and I settled on DMF and EPLS as our first targets.

[Per HHS's OIG](https://oig.hhs.gov/faqs/exclusions-faq.asp), it looks like EPLS is a superset of LEIE:

    What is the difference between the LEIE and the General Services
    Administration's (GSA) Excluded Parties List System (EPLS) and
    System for Award Management (SAM) websites?

    GSA administers EPLS and SAM, both of which contain debarment
    actions taken by various Federal agencies, including exclusion
    actions taken by the OIG. The List of Excluded
    Individuals/Entities contains only the exclusion actions taken by
    the OIG. You may access the EPLS at: http://www.epls.gov External
    link and SAM at https://www.sam.gov External link.

@brainwane, can you confirm that EPLS is a superset of LEIE? Thanks!

**Comment by cecilia-donnelly** [comment]
Some questions to ask about these federal data sources (for @brainwane and everyone): 

   - Do they have dev/test versions that we could use while in development?  (A sample data file or test API, perhaps.)
   - What are their gating mechanisms?  Can we easily use their authorization checks?  That is, do we need to set up some authorization system for states or can we use one that's already built into the data source?

**Comment by brainwane** [comment]
@jvasile I'm researching to double-check that question right now.

**Comment by cecilia-donnelly** [comment]
Some more background on SAM/EPLS/LEIE: http://blog.providertrust.com/blog/OIG-LEIE-vs-SAM.gov-OMG

**Comment by cecilia-donnelly** [comment]
Subscription options and sample code for accessing the Death Master File are available [here](https://www.ssdmf.com/FolderID/97/SessionID/%7B43FD1DB0-2F5B-4539-A5CE-149B675B6764%7D/PageVars/Library/InfoManage/Guide.htm).

**Comment by cecilia-donnelly** [comment]
CSV download for LEIE: https://oig.hhs.gov/exclusions/exclusions_list.asp

**Comment by brainwane** [comment]
For the Death Master File, there does not seem to be an official source of sample data, but http://ssdmf.info/ provides a downloadable sample from 30 November 2011.

The schema of the ssdmf.info file does not entirely match the schema presented in https://dmf.ntis.gov/recordlayout.pdf . But the sample file has a consistent layout. Differences:

* "name suffix" is very rarely present, and the fieldsize/position is off by one: 30-33 instead of 31-34.
* The middle name does not have a multi-character field, but a middle *initial* (a single character) is present.

**Comment by brainwane** [comment]
As @cecilia-donnelly noted, CSV download for LEIE is at https://oig.hhs.gov/exclusions/exclusions_list.asp ; the April download is at https://oig.hhs.gov/exclusions/downloadables/UPDATED.csv . It seems to be updated monthly. My visual inspection of the April download shows that it's consonant with the schema as described in https://oig.hhs.gov/exclusions/files/leie_record_layout.pdf .

**Comment by kfogel** [comment]
Thanks for the format information, @brainwane.  Are there any "Terms of Use" restrictions or other legal/bureaucratic hurdles associated with any of these data sets?  (We need to make sure we're entirely in the clear for anything we use for dev or production.)

**Comment by kfogel** [comment]
Hey, @brainwane, I'm going to delete my previous comment -- it's out of scope for the investigation you're doing, and I didn't mean to distract!  Just posting this first as a kind of "commit message" for the deletion I'm about to do.

**Comment by jvasile** [comment]
@brainwane, what about the 2013 ssdmf sample?  Does it match the modern dmf schema?

**Comment by brainwane** [comment]
@jvasile The 2013 ssdmf sample (as found at http://cancelthesefunerals.com/ ) is -- from a visual inspection -- consistent with the 2011 sample. That is to say:

* it also has a middle *initial* field rather than a multi-character field for a middle name
* the fieldsize/position for "name suffix" is off (30-33 instead of 31-34 -- also, sometimes, the name suffix is immediately following the "Last Name", e.g., HARIHARESWARA JR with only a single space in between)

**Comment by cecilia-donnelly** [comment]
We received the official DMF file layout.  It is:

```
ID | Name        | Description                                                        | Type | Length
------------------------------------------------------
1 | NPI            | National Provider Identifier, a unique identification    | CHAR | 10
                   |  number for health care providers                        |
2 | SSN4           | Last four digits of the individual's SSN                 | CHAR | 9
3 | PRSN_LAST_NAME | Last name of the individual                              | CHAR | 20
4 | PRSN_1ST_NAME  | First name of the individual                             | CHAR | 15
5 | DOB_RAW_TXT    | Birth date of the individual                             | CHAR | 8
6 | DOD_RAW_TXT    | Death date of the individual                             | CHAR | 8
```

**Comment by jvasile** [comment]
I'm going to close this.  We've chosen a first ETL target, which is LEIE.  We have real data and it has a simple ETL process attached to it.  There is other data source work to do, but we've met the goal of this issue.  Thanks, all!
