### ISSUE TITLE
Registration confirmation page needs contact link, APPNAME substitution

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#176]
After a user self-registers, the confirmation message on, for instance, http://localhost:8080/cms/accounts/confirm?id=brtest&token=TcRPiZrwtSfeVNBVfGaxYnX77d0%3D is:

> You have been successfully registered to APPNAME.

We should substitute in an appropriate name. Also, "in" might be better than "to".

![psm-reg-to-appname](https://user-images.githubusercontent.com/842790/27245559-53c241bc-52ba-11e7-93bc-04966ed5df44.png)

**Comment by brainwane** [comment]
This page also has a contact link that does nothing and should provide a contact email or dialog:

`If you do not receive the email within a reasonable amount of time, please <a href="#">contact us</a> and we`

**Comment by jasonaowen** [comment]
Does #389 capture the contact link concern? If so, we can narrow this issue to just the "APPNAME" thing, and then we can mark #525 as resolving this.

**Comment by brainwane** [comment]
I think you're right! Revising accordingly.
