### ISSUE TITLE
change capabilities in README to given-when-then format

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#186]

**Comment by jasonaowen** [comment]
@brainwane can you say more about this? Was it related to laying the groundwork for the BDD UI tests, which we now have? If not, what is the motivation for changing the format?

**Comment by brainwane** [comment]
Yes, this was to lay better groundwork for BDD UI tests -- it was @BenGalewsky's idea, if I recall correctly.

**Comment by jasonaowen** [comment]
Great! We have BDD UI tests; does that mean we can mark this issue as resolved?

**Comment by brainwane** [comment]
Yeah, sounds good to me.
