### ISSUE TITLE
Auto-deploy EAR File Generated by Build

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#189]
# Problem
We have a gradle build that can generate an EAR file, but the process stops there. For a CI process we need to be able to deploy the generated application to a sandbox instance.

The best solution would be to update the Dockerfile to include the EAR file in the docker image. The database docker container would have a startup step that builds the database from `seed.sql` and `legacy_seed.sql` so that the end result is a complete installation of the application, ready for testing.

Another issue would be how to deploy the docker compose environment upon build. The natural solution would be a Kubernetes cluster.

**Comment by jasonaowen** [comment]
I think this is the same as #222. That issue was opened later, but has had more discussion, so I suggest we close this one. @cecilia-donnelly ?

**Comment by cecilia-donnelly** [comment]
Good catch @jasonaowen.  Sorry for the duplicate issue, @BenGalewsky!
