### ISSUE TITLE
Investigate data_load subproject

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#205]
The `data_load` subproject has some similar classnames to the main `psm-app` project.  It came up in https://github.com/OpenTechStrategies/psm/pull/140#issuecomment-309120275, and may be implicated in the current error on creating new provider types.  (To reproduce: log in as an admin, click on "Functions," and click "Add Provider Type.")

Find out the purpose of the `data_load` subproject, determine whether we still need it, and if so, what needs to be done to make it work correctly.

**Comment by jasonaowen** [comment]
@BenGalewsky: can you please write up more about what you've learned?

From #211, where you recommend deletion:
> Looked into the data_load sub-project in the repo. It uses ant tasks to perform two ETL operations that load lookup data used in the enrollment synchronization processes. Upon reflection, these processes will require significant enhancement to work in a multi-state environment. Consequently, there is little likelihood that these lookup tables and ETL tasks would be re-used in the current format.

Can you say more about the data? Can you say more about enrollment synchronization? With what were enrollments being synchronized? What kinds of enhancements do you think would be needed?
