### ISSUE TITLE
Confirm which data handling standards we need to comply with

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#21]
If we are going to get set up as a data wrangler of various data sources, I want to be able to check that we are following any MITA or CMS standards that are appropriate for handling provider info. I presume that *provider* info could not possibly constitute sensitive PII but I would like to double-check this!

I started looking at [the MITA framework](https://www.medicaid.gov/medicaid/data-and-systems/mita/mita-30/index.html) but think it does not address this question.

I am beginning to think that the relevant standards might well be ["Minimum Acceptable Risk Standards for Exchanges (MARS-E) 2.0 Framework"](https://www.cms.gov/CCIIO/Resources/Regulations-and-Guidance/Downloads/2-MARS-E-v2-0-Minimum-Acceptable-Risk-Standards-for-Exchanges-11102015.pdf) -- discussed privately [on CALT]( https://calt.cms.gov/sf/projects/cms_aca_program_security_privacy/) and publicly listed in [cms.gov's Regulations and Guidance](https://www.cms.gov/cciio/resources/regulations-and-guidance/#MinimumAcceptableRiskStandards), explained in [this summary from CMS (pdf)](https://www.medicaid.gov/federal-policy-guidance/downloads/cib-09-23-2015.pdf) and described in [this surprisingly cogent Microsoft compliance page](https://www.microsoft.com/en-us/TrustCenter/Compliance/Mars-E). But I haven't gone deeply enough into it to understand whether it applies just to patients or includes any discussion of providers as well.

And I stumbled across a [NIST standard, "Guide to Protecting the Confidentiality of Personally Identifiable Information (PII)" (pdf)](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf) -- but this only applies if any of the data we deal with counts as PII.

The resolution of this issue may depend on which federal data services we integrate with, in which case we can close it as a duplicate of #17.

Relates to #10.

**Comment by kfogel** [comment]
+1 -- thanks for thinking of this, @brainwane.

**Comment by jvasile** [comment]
MARS-E is for exchanges and doesn't apply here.

We have PII for some providers and we should take steps to protect it, but I can't find any federal regulations that mandate specific standards.  At any rate, industry standard protection should suffice and obviously leaking such data constitutes a bug.  We don't need to do specific work on this issue except to continue our work on building secure infrastructure with sane access controls.
