### ISSUE TITLE
Add an API to ETL results

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#224]
Anything we pull in via ETL should be available MMIS-wide via a RESTful API.  For now, we need to make it available to the rest of the module so that the exclusions list is consulted automatically when a new enrollment is submitted.  The first pass at this will likely not include auth, but down the road we may want to use OAuth 2.

**Comment by jvasile** [comment]
This is addressed in [PR 271](https://github.com/OpenTechStrategies/psm/pull/271).  Once that's meged, we can close this.

**Comment by cecilia-donnelly** [comment]
Hey @jvasile -- is this done?  Should I open a separate issue for documenting the API, or do you want to include that in this one?

**Comment by cecilia-donnelly** [comment]
We have a working and reasonably documented API.  Closing.
