### ISSUE TITLE
Address entry / preservation problems for Additional Practice Location.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/psm#282]
As reported by Judy Cunard in [this post](https://groups.google.com/d/msg/psm-dev/CoynozmCWfI/3f2zy6gABwAJ), there are some bugs with the address fields on the Additional Practice Location page.  The bugs involve preservation of information & positioning across backwards and forwards page changes, as well as the fact that County is not a drop-down menu (which is now separate bug #283).  Judy provided a narrative reproduction recipe in an attachment; that document is attached here as well.

[PSM Scenario Screen Shots 06302017.docx](https://github.com/OpenTechStrategies/psm/files/1160829/PSM.Scenario.Screen.Shots.06302017.docx)

**Comment by jasonaowen** [comment]
If you add an additional practice location to an individual enrollment, only the second address line of that additional practice location is saved; the first line is thrown away. If you go in as the admin and edit the enrollment, or if you view the enrollment (either as a provider or as the admin), the second address line is moved to the first line.

If you only add one line (either line 1 or line 2), it is persisted correctly.

![282-addtional-address-1-set](https://user-images.githubusercontent.com/1494855/29734790-324c914c-89c2-11e7-88a4-754083257985.png)

![282-addtional-address-2-edit](https://user-images.githubusercontent.com/1494855/29734751-fb82e65c-89c1-11e7-90f4-d0a7b6c67691.png)
![282-addtional-address-3-review](https://user-images.githubusercontent.com/1494855/29734748-fb7fcd3c-89c1-11e7-987b-926dd4e49a33.png)

**Comment by cecilia-donnelly** [comment]
@jasonaowen fixed this in #437.
