### ISSUE TITLE
Use LEIE API to automatically screen providers

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#289]
@jvasile has added a draft API to the LEIE data he's pulled in via ETL, as described in #224.  Per conversation in #17, this LEIE data corresponds to the "EXCLUDED PROVIDER VERIFICATION IN OIG (checked means not in exclusion list)" checkbox on the admin review screen:

![screenshot from 2017-07-24 09-52-43](https://user-images.githubusercontent.com/1497818/28529326-dff2e4d0-7055-11e7-8c5c-99e6610052d6.png)

To automatically screen, the PSM should check the LEIE API for the provider with the name and/or NPI and/or tax id given in the enrollment (however the API expects to be called).  If the provider is in the exclusions list, the checkbox should be left unchecked.  If the provider is not found in the exclusions list, the checkbox should be checked.  In either case, an audit log should appear linked from the "View" link in the Auto Screening column (currently no screening is done):

![screenshot from 2017-07-24 10-09-46](https://user-images.githubusercontent.com/1497818/28530118-4edeabe8-7058-11e7-86ff-3de993b524f4.png)

**Comment by jasonaowen** [comment]
This is working! Concerns raised during review of #345 have been addressed or have issues to track them.

I think this is ready to be closed. @cecilia-donnelly, if you agree, would you please do the honors?

**Comment by cecilia-donnelly** [comment]
Yes!  Thanks, @jasonaowen :)
