### ISSUE TITLE
Add 4 extra digits to zipcode field(s)

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#290]
Wherever a form asks for a zipcode, add space for the 4 additional digits.

**Comment by jasonaowen** [comment]
Good news! This functionality already seems to be in place. We probably want to go through and change the CSS/HTML to make the zip codes bigger so as to visually suggest that they will accept more than 5 digits, but all the zip code fields I can find do accept 10 characters (including the `-`).

I went through the enrollment process as both an individual and a organizational provider, and filled in the practice location, additional practice location, billing location, organization location, individual owner location, and organization owner location - all of them accepted a full 9-digit zip code (plus the `-` separator) without error, persisted it, and were visible to the admin during viewing and editing.

**Comment by cecilia-donnelly** [comment]
I'll expand the zip code fields so this is more obvious.  Then we can close this.

**Comment by jasonaowen** [comment]
I just found a spot that doesn't accept 10 digits: the Personal Care Assistant form is different from the one used by most other individual providers, and only accepts 6 digits:

![screenshot 2017-09-20 16 31 31](https://user-images.githubusercontent.com/1494855/30666111-4b3c7f3c-9e21-11e7-9be5-0cb934eb8035.png)

**Comment by cecilia-donnelly** [comment]
Ooh good find, @jasonaowen!  I'll look into it.
