### ISSUE TITLE
Verify that initial requirements are met

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#291]
- [x] The PSM shall ensure that tax ID number is 9 digits
- [x] The PSM shall allow applicant to upload attachments to support the application.
- [x] The PSM shall accept the following fields: Applicant Name, Contact Person, Contact phone, Medicaid number
- [x] The PSM shall separate providers into risk categories limited, moderate, and high based on provider type, as established by CMS.
- [x] The PSM shall provide a screen to verify entered information.
- [x] The PSM shall allow applicant to edit entered information.
- [x] The PSM shall allow applicant to print application for their records.
- [x] The PSM shall allow applicant to save a partial application as a draft.
- [x] The PSM shall indicate what kinds of documents/attachments are required by provider type.
- [x] The PSM shall validate entered information as provider fills out application (not at the end of the process).

I believe that these requirements are met with the current state of the PSM.  Some of them can be verified manually, while others should be tested with Selenium.  If any of them are not met, please open an issue to fix them.  (If it's better to separate these into individual issues we can do that too.)

**Comment by jasonaowen** [comment]
> The PSM shall separate providers into risk categories limited, moderate, and high based on provider type, as established by CMS

Risk levels in the PSM are assigned by Drools rules based on the provider type. Here are the relevant rules:
- [Physical Therapists are moderate risk](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2069-L2087)
- [All other individual provider types are limited risk](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L305-L322)
- [The following organizational provider types are moderate risk](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2228-L2245):
    - Community Mental Health Center
    - Independent Diagnostic Testing Facility
    - Independent Laboratory
    - Medical Transportation
    - X-Ray Services
- [The following organizational provider types are high risk](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2259-L2269), (except [when renewing, when they are moderate risk](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2247-L2257)):
    - Durable Medical Equipment
    - Home Health Agency
- Rehabilitation Agencies are...
    - [moderate risk if they have a CORF (Comprehensive Outpatient Rehabilitation Facility) certification](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2271-L2283)
    - [limited risk if they do not have a CORF certification](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2285-L2297)
- [All other organizational provider types are limited risk](https://github.com/OpenTechStrategies/psm/blob/3ac7ba0b5b130b45bb5f30be14bb88cda414e551/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2206-L2226)

**Comment by cecilia-donnelly** [comment]
The CFR names [levels of risk for most provider types](https://www.law.cornell.edu/cfr/text/42/424.518).  Our risk level assignments follow those rules.

**Comment by jasonaowen** [comment]
> - The PSM shall indicate what kinds of documents/attachments are required by provider type.
> - The PSM shall validate entered information as provider fills out application (not at the end of the process).

We think we meet these requirements. The license upload page makes it clear what document is needed in most cases by pre-populating the license type drop-down with the single allowed option. In some cases, where the requirement is something more like "Either License A or (License B and Certification C)", the drop-down has all three options, and trying to move past without the correct set of documents results in a descriptive error.

Other forms have a similar validation process, where missing or incorrectly formatted data is called out on the page before submission, rather than at submission time.
