### ISSUE TITLE
Label all required fields

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#292]
We have some related requirements about required fields:

- [x] The PSM shall indicate which fields are required.
- [x] The PSM shall require the following fields: Provider Name, Business Phone, Provider Street Address, City, State, Zip Code, County, SSN, Date of Birth, License Number, IRS Payee Name, DBA Name, Payee Address, Payee City, Payee State, Payee Zip Code, Payee Tax ID, Provider Email address
- [x] The PSM shall automatically reject applications that do not include all mandatory information.
- [x] The PSM shall prevent application submission if required fields are empty.

In most places, we have red asterisks to indicate required fields, meeting the first requirement (though we need a thorough review to make sure that *all* required fields are so indicated).  The auto-rejection and submission-prevention items work in the cases I've reviewed -- a Selenium test to spot-check those would be helpful.

**Comment by brainwane** [comment]
IMO this would be substantially easier if we resolved #238.

**Comment by jasonaowen** [comment]
@brainwane can you please say more about why you think that? We may have different conceptions about what that issue means.

**Comment by brainwane** [comment]
My thinking is basically that if we have a set of UI templates then it'll be easy to implement a "required" flag that then ensures the styling of that field (asterisk, boldface, any other formatting) and to wire up logic saying that all the required fields must be filled/selected before being able to proceed. But perhaps I am wrong!

**Comment by cecilia-donnelly** [comment]
Missing "required" indicator:
- The first input field for "Home Residence Address" under "Individual Person(s) Ownership or Control Interest" (for an organizational provider) does not have the red outline when it is left empty (on submit, other fields that were mistakenly left empty get this red marker)

**Comment by jasonaowen** [comment]
These are all done!
