### ISSUE TITLE
Determine Oracle-specificity / PostgreSQL-compatibility of existing SQL.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/psm#3]
Let's determine what (if anything) needs to be done to make the SQL PostgreSQL-compatible.  We might want to start by getting our past research on the status of the PSM's SQL out here into public view.

**Comment by jasonaowen** [comment]
Between #1 and #36, I think we've found and exercised all the SQL in the application, and ensured that it works with PostgreSQL.
