### ISSUE TITLE
"System error" on creating user (though creation succeeds)

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#340]
When I'm logged in as the `system` user and create a new provider-type user, I get a "System Error" page after hitting "Save."  The new user is, however, created correctly.  I think this is a regression -- at one point I believe creating users brought us to some kind of success page.

**Comment by cecilia-donnelly** [comment]
I also get an error when editing a user, but editing does *not* appear to work correctly.  (e.g., renaming a user from `excluded` to `excluded1` does not succeed)

**Comment by jasonaowen** [comment]
@cecilia-donnelly do you have a mail server running? Mailcatcher, or the Python smtpd debugging module?

**Comment by cecilia-donnelly** [comment]
@jasonaowen I don't!  That would explain it, thanks.
