### ISSUE TITLE
Capture Medicaid Number for new Enrollments

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#347]
# Problem
Requirement psm-2.9 states that PSM application shall accept a medicaid number for new enrollments. There is no field for this value.

Add this field to the ~individual and~ organizational info page~s~ in the enrollment workflow and update the serenity tests to confirm.

**Comment by jasonaowen** [comment]
Looking at the [referenced source document](https://github.com/OpenTechStrategies/psm/blob/33d87d1912306839a68860006020d0a2117f069b/requirements/MO/MISSOURI%20MEDICAID%20PROVIDER%20ENROLLMENT%20INFORMATION%20GUIDE.docx), the only instance of the string "Medicaid Number" is on page 44, under "MO HealthNet Provider Enrollment Application Part 2 Help":

> Clinic/Group Medicaid Number:
> Enter the clinic or group MO HealthNet number where the applicant is providing services.

["Missouri's Medicaid program is called MO HealthNet"](https://mydss.mo.gov/healthcare). Searching for "MO HealthNet number", I found some documents that say this will be a 9-digit number; I can't tell if there's a check digit built in, like with NPIs.

So, how do want to handle this in the PSM? Shall we have a free-form text field with a name like "State Medicaid Provider Number"? We probably don't want to specifically call out Missouri's program; do we want some kind of compile-time or run-time configurable option to change the display name of this state Medicaid provider number? Do other states have something similar?

**Comment by cecilia-donnelly** [comment]
Thanks for looking at this @jasonaowen.  

I think for now we can add a free-form text field with "State Medicaid Provider Number," yes.  Other states will have these numbers (we had a brief discussion in IRC a while ago):

>cdonnelly: medicaid number is the state version of the NPI
cdonnelly: I mean, that's an oversimplification, but providers are assigned numbers when they enroll in a state's medicaid program

Based on the original source, we probably only need to add this new number for providers that are enrolling as part of a group.  Currently we collect the name, address, and NPI of the group.  We can add this new field there.

**Comment by jasonaowen** [comment]
After talking more in IRC with @cecilia-donnelly, here's our updated understanding of the problem we're trying to solve.

- A group provider (say, a hospital) enrolls in a state's Medicaid program (perhaps through the PSM, perhaps before the PSM was put into production). The state approves the provider, and issues them a state-specific "State Medicaid Provider Number".
- An individual provider joins the group (say, a doctor joining the hospital), and the state needs the group's state Medicaid provider number to link the individual to the group practice.

Here's where the new field will go:
![Form which needs the new "State Medicaid Provider Number" field](https://user-images.githubusercontent.com/1494855/29732777-2ddd4e58-89b8-11e7-86d3-a2d7e5707d2f.png)

There may be related requirements around renewal / revalidation. As we learn more about that process and our requirements around it, we'll open up additional issues as we need them.

**Comment by jasonaowen** [comment]
Given our *current* understanding of the requirements, I intend to add a new column to the `organizations` table, which correlates to a new field in the [`Organization` entity](https://github.com/OpenTechStrategies/psm/blob/a24437b3ebda38e0597a08fdeca64150370fe84f/psm-app/services/src/main/java/gov/medicaid/entities/Organization.java#L27). If it turns out all entities will need this, we can promote it to the `entities` table / `Entity` entity.
