### ISSUE TITLE
Deploy external sources app on Wildfly

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#35]
Get the `ext-sources-app` part of the repository running on Wildfly.  This will probably involve some of the same work as #2.

**Comment by jvasile** [comment]
I started a branch, [wip-ext-sources](https://github.com/OpenTechStrategies/psm/tree/wip-ext-sources), to work on this. @slifty and @jasonaowen feel free to jump in.

**Comment by kfogel** [comment]
Should we have a convention of starting branch names with the associated issue number, when there is one?  E.g., this branch would be `35-wip-ext-sources`.

I like that convention (and did not invent it :-) ).  If we agree, I'll make a PR to add it to CONTRIBUTING.md.

(Asking here b/c it was seeing this branch that made me think of it.)

**Comment by cecilia-donnelly** [comment]
@slifty will be posting to the list about possible routes forward here.  For now, let's hold off on standing up the existing external sources app.

**Comment by jvasile** [comment]
+1 to Kfogel's convention, which I hereby deem "kfogel's cfonvention" if it works and "kfogel's kfolly" if it does not.

**Comment by kfogel** [comment]
kthxbye, @jvasile

**Comment by jvasile** [comment]
After @slifty's analysis that the existing ext-sources code is a dead end, I'm closing this.
