### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by stephenwaite** [OpenTechStrategies/psm#350]
hi, here's the broken link:

http://www.topcoder.com/cms/medicaid-enrollment-portal/

**Comment by brainwane** [comment]
Thanks for reporting this issue, @stephenwaite! I've now updated the `README` to point to an archived version of that page: https://web.archive.org/web/20141111041442/http://www.topcoder.com:80/cms/medicaid-enrollment-portal/ .

**Comment by stephenwaite** [comment]
cool, thanks for the quick fix, enjoying learning about the project

**Comment by stephenwaite** [comment]
hi @brainwane , also noted this typo [here](https://github.com/OpenTechStrategies/psm#section-2-background)

>  identify authentication

**Comment by brainwane** [comment]
Thanks, @stephenwaite! Fixed.

Feel free to join us in the #opentechstrategies IRC channel on Freenode ([here's an easy link to do that in your web browser, in case you do not currently use an IRC client](https://webchat.freenode.net/?channels=%23opentechstrategies)) to talk more about the project!

**Comment by stephenwaite** [comment]
you're welcome, thanks for the response.  I'm a noob with IRC but I'll hop on the web, thank you.
