### ISSUE TITLE
Use Hibernate 5, instead of 4

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#36]
The PSM had been using Hibernate 4.  Wildfly 10, our application server (see #2), ships with Hibernate 5.  Upgrade the code to work with the new version of Hibernate.

The full list of classes that need to be transformed is:

- [x] AcceptedAgreements
- [x] Address
- [x] Affiliation
- [x] AgreementDocument
- [x] Asset
- [x] AssuredService
- [x] AuditDetail
- [x] AuditRecord
- [x] Authentication
- [x] BeneficialOwner
- [x] BeneficialOwnerType
- [x] BinaryContent
- [x] CategoryOfService
- [x] CMSUser
- [x] ContactInformation
- [x] CountyType
- [x] Degree
- [x] DesignatedContact
- [x] Document
- [x] Enrollment
- [x] EnrollmentStatus
- [x] Entity
- [x] EntityStructureType
- [x] Event
- [x] ExternalAccountLink
- [x] ExternalProfileLink
- [x] HelpItem
- [x] IssuingBoard
- [x] LegacySystemMapping
- [x] License
- [x] LicenseStatus
- [x] LicenseType
- [x] Note
- [x] OwnershipInformation
- [x] OwnershipType
- [x] PayToProvider
- [x] PayToProviderType
- [x] ProfileStatus
- [x] ProviderCategoryOfService
- [x] ProviderProfile
- [x] ProviderService
- [x] ProviderStatement
- [x] ProviderType
- [x] ProviderTypeSetting
- [x] QPType
- [x] RelationshipType
- [x] RequestType
- [x] RequiredField
- [x] RequiredFieldType
- [x] RiskLevel
- [x] Role
- [x] ScreeningSchedule
- [x] ServiceAssuranceExtType
- [x] ServiceAssuranceType
- [x] ServiceCategory
- [x] SpecialtyType
- [x] StateType

Some of these have already been transformed. We'll keep track of progress in this issue. (@jasonaowen, please respond with any corrections.)

See [the wip-hibernate branch](https://github.com/OpenTechStrategies/psm/tree/wip-hibernate) for progress on this issue.

**Comment by cecilia-donnelly** [comment]
@jasonaowen has been transforming the classes in [Medicaid.hbm.xml](https://github.com/OpenTechStrategies/psm/blob/master/psm-app/cms-business-process/src/main/resources/META-INF/Medicaid.hbm.xml) to annotations in [persistence.xml](https://github.com/OpenTechStrategies/psm/blob/master/psm-app/cms-business-process/src/main/resources/META-INF/persistence.xml) as described in [this thread](https://groups.google.com/forum/#!topic/psm-dev/LTpeFH218Kg).  

The full list of classes that need to be transformed is:

- [ ] Authentication
- [ ] Enrollment
- [ ] Address
- [ ] Affiliation
- [ ] PayToProvider
- [ ] AssuredService
- [ ] ContactInformation
- [ ] RequestType
- [ ] BeneficialOwnerType
- [ ] EntityStructureType
- [ ] RelationshipType
- [ ] QPType
- [ ] ServiceCategory
- [ ] CategoryOfService
- [ ] OwnershipType
- [ ] Role
- [ ] Degree
- [ ] EnrollmentStatus
- [ ] RiskLevel
- [ ] ProfileStatus
- [ ] SpecialtyType
- [ ] ProviderType
- [ ] LicenseType
- [ ] StateType
- [ ] CountyType
- [ ] LicenseStatus
- [ ] IssuingBoard
- [ ] PayToProviderType
- [ ] ServiceAssuranceType
- [ ] ServiceAssuranceExtType
- [ ] ProviderProfile
- [ ] DesignatedContact
- [ ] License
- [ ] BinaryContent
- [ ] Document
- [ ] AgreementDocument
- [ ] AcceptedAgreements
- [ ] ProviderStatement
- [ ] Note
- [ ] CMSUser
- [ ] ExternalAccountLink
- [ ] ExternalProfileLink
- [ ] OwnershipInformation
- [ ] Asset
- [ ] ProviderTypeSetting
- [ ] ProviderService
- [ ] ProviderCategoryOfService
- [ ] Event
- [ ] RequiredFieldType
- [ ] RequiredField
- [ ] ScreeningSchedule
- [ ] HelpItem
- [ ] LegacySystemMapping

Some of these have already been transformed.  We'll keep track of progress in this issue.  (@jasonaowen, please respond with any corrections.)

**Comment by jasonaowen** [comment]
I wrote up some notes to myself that others might find useful in converting these over:

---

#### Converting an `IdentifiableEntity` from Hibernate 4 to 5

1. Remove node from `Medicaid.hbm.xml`
2. Add class to `persistence.xml`
3. Add line to `DROP TABLE` in `seed.sql`
4. Add table definition to `seed.sql`
   1. Maybe add sample data to `seed.sql`
5. Update class
   1. replace `extends IdentifiableEntity` with `implements Serializable`
6. Delete sequence name and its usages in `Sequences`

#### Converting a `LookupEntity` from Hibernate 4 to 5

1. Remove node from `Medicaid.hbm.xml`
2. Add class to `persistence.xml`
3. Add line to `DROP TABLE` in `seed.sql`
4. Add table definition to `seed.sql`
   Maybe add sample data to `seed.sql`
5. Update class

**Comment by cecilia-donnelly** [comment]
See this [Kanban board](https://tree.taiga.io/project/ots-psm-hibernate-conversion/kanban), where we'll be tracking progress on this now that more people are working on different classes.  The checklist above may fall out of date -- the Kanban board is now the One True Master.

**Comment by cecilia-donnelly** [comment]
@jasonaowen, can we close this one?  (!!!)  I'll let you do the honors, if it's ready.

**Comment by jasonaowen** [comment]
@cecilia-donnelly almost! Just a few left; I've been so focused on other stuff I haven't yet pushed the remaining work I'd done. I'll do that now!
