### ISSUE TITLE
Individual Beneficial Owner City Field Doesn't Pick up Entered Value

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#362]
# Problem
When enrolling an organizational provider users are asked to provide information on the organization's beneficial owners. One field, the owner's city ignores entered data on the first submit. After showing an error page and users re-enter the city it is accepted.

# Diagnostics
An inspection of the page shows that the field is initially defined as

```<input type="text" class="cityInputFor" name="_17_iboOtherZip_0" value="" maxlength="18">```

After form submission, the input changes, both to reflect the error condition, but also the field name has changed:

```<input type="text" class="cityInputFor errorInput" name="_17_iboOtherCity_0" value="" maxlength="18">```

# Tasks
- Fix the field naming
- Verify that the form accepts the city on the first try.

**Comment by cecilia-donnelly** [comment]
Fixed by @BenGalewsky in #367.
