### ISSUE TITLE
GitHub Wiki?

### ISSUE THREAD

**Issue by jvasile** [OpenTechStrategies/psm#45]
GitHub has a wiki.  We don't use it, but the link is there in case somebody wants to contribute.  I'm inclined to disable it because we are not going to garden the wiki.  I'd rather see changes go in to the md files in the repo.  There is a cost, of course, which is that we close off an avenue of participation from people who aren't git-savvy.  Still, I move we disable the wiki and direct those people to the mailing list.

**Comment by brainwane** [comment]
I second your suggestion, James.

**Comment by cecilia-donnelly** [comment]
+1 and I will do this.  We can always turn it back on if there's a need.

**Comment by kfogel** [comment]
Fourthed, FWIW.

**Comment by slifty** [comment]
(...fifthed!)
