### ISSUE TITLE
Bad link on admin view

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#455]
When administrators click in to "Edit" a Pending enrollment, they see a link to "Enrollments" in the breadcrumb at the top of the screen:

![screenshot from 2017-09-27 12-02-41](https://user-images.githubusercontent.com/1497818/30926984-91791266-a37c-11e7-8020-f73e6b883b5c.png)

That link claims to direct to 'cms/cms/provider/dashboard/drafts', but when clicked it gives a 404:

![screenshot from 2017-09-27 12-02-45](https://user-images.githubusercontent.com/1497818/30927096-e813768e-a37c-11e7-9be5-86f67ba03f1e.png)

**Comment by brainwane** [comment]
Just ran into this.
