### ISSUE TITLE
Simple search (field in upper right) fails to find results

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#496]
As a service admin, I used the simple search field to search for a substring of a provider name ("DME") on my local copy.  The provider "DME Test" had submitted two enrollments, and the provider "DME" had submitted one as well, so I would expect one or more of those to turn up in search results.  None did.  Similarly, @jcunard mentioned [on the list](https://groups.google.com/forum/#!topic/psm-dev/q-XGEsndkhA) that the search failed to find her user profile.

**Comment by cecilia-donnelly** [comment]
See also #174 -- @brainwane, do you think this is a duplicate?

**Comment by brainwane** [comment]
I do think it's a duplicate; closing. Thanks, Cecilia.
