### ISSUE TITLE
Presentability: use generic PSM logo

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/psm#51]
The PSM should have a generic (non-state-specific) logo for dev/demo sandboxes, etc.

Note that this ticket also used to include another presentability concern: getting rid of the "lorem ipsum" nonsense text in the UI, e.g., on the login page.  However, that is now tracked in issue #108.

**Comment by kfogel** [comment]
Three logo options (thanks @fdooli):

![psm_logo_options](https://user-images.githubusercontent.com/401111/26915894-8aede804-4bed-11e7-8fac-8608f012e6fc.png)

Attaching original PDF below:

[PSM_logo_options.pdf](https://github.com/OpenTechStrategies/psm/files/1060150/PSM_logo_options.pdf)

**Comment by jasonaowen** [comment]
Is the intent to choose between the variants (with/without "Provider Screening Module"), or are they going to be used as a pair, depending on where in the application the logo is used?

**Comment by cecilia-donnelly** [comment]
@jasonaowen I think the second -- sometimes we'll have "Provider Screening Module" text and sometimes not.

**Comment by brainwane** [comment]
I like the third option, the one that suggests a funnel.

**Comment by jasonaowen** [comment]
Oh I didn't vote! I like the first one. :two_men_holding_hands: :two_women_holding_hands:

**Comment by cecilia-donnelly** [comment]
Darn, I like the second one...I can feel a consensus building.

**Comment by slifty** [comment]
I'm a fan of the first one also -- the second and third look too much like dollar signs to me, it throws me off!

**Comment by bycheng1** [comment]
I like the second one.  I am on team Cecilia...

**Comment by jcunard** [comment]
Sorry Bill and Cecilia, #1.

**Comment by jvasile** [comment]
Logo #1 all the way.

**Comment by jvasile** [comment]
What's an election without real time updates?  With just a small handful of votes counted, CNN isn't quite ready to call it for Logo 1, though their projections say Logo 3 will take Florida in a surprising upset.


First logo:

Ben
Dan
Jason
Jcunard
James

Second logo:

Cecilia
Bill

Third logo:

Sumana
