### ISSUE TITLE
Travis/Sauce Labs disconnection problem?

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#533]
Our Travis Build \#1193, which was run when I merged PR #529, Sauce Labs wasn't able to start the job:

```
        net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.remote.RemoteWebDriver (Sauce could not start your job. For more information on what happened, please visit {Sauce Labs link here} (WARNING: The server did not provide any stacktrace information)
```

Sauce Labs Test Details tells me "Your test errored. No active tunnel found for identifier 1193.1"

Do you have any ideas about this, @slifty?

Earlier in the Travis log for \#1193, I see:

```
E: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  503  Service Unavailable [IP: 64.50.233.100 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
<sub>Side note: why is the OSL not using HTTPS?</sub>

That subdir does indeed seem to be empty, so I'm not sure why we're trying to fetch it.  The last successful build on master was \#1172, which didn't have this problem.

On the other hand, build \#1196 succeeded and appears to have run the Sauce Lab tests correctly.

**Comment by slifty** [comment]
@cecilia-donnelly is this continuing to happen consistently?  If not, it will be hard to diagnose or fix.

My bet right now is that it was a temporary network-level issue.  If it's only happened once then we may want to either close this issue or leave it open as a place to log that kind of problem until we have enough instances to form a pattern.

**Comment by jasonaowen** [comment]
This might have been related to [a Sauce Labs service incident](https://status.saucelabs.com/incidents/j9myxvplfrp3), although the times don't really line up. Hopefully having clearer logs will help if this problem happens again. I'm :+1: to close this for now as a temporary outage.

**Comment by cecilia-donnelly** [comment]
Thanks you two!  Makes sense to me.  We can open it again if necessary.

**Comment by jasonaowen** [comment]
We had this problem again today. It seems to have been a transient issue, as waiting a bit and restarting the builds resulted in passing tests.
