### ISSUE TITLE
Create an .editorconfig

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/psm#56]
#42 has a few folks who contributed and we already have some whitespace conflicts (mix of tabs and spaces).

Would it be worth setting up an .editorconfig so we could prevent the need for future whitespace-only commits?

**Comment by kfogel** [comment]
Yes.  And adding a "no tabs" policy to CONTRIBUTING.md :-).

(I have all the usual justifications for having that preference, and am apparently [not alone](http://blog.takipi.com/tabs-vs-spaces-how-they-write-java-in-google-twitter-mozilla-and-pied-piper/).)

**Comment by jasonaowen** [comment]
+1 to both of those things.

One of my plans, once we convert from ant to gradle (in #16), is to include the IntelliJ plugin to generate the IDE's project configuration; settings like this are part of that.

@kfogel as part of the "no tabs" policy, I think it would be useful to have a contributing guideline of "if you work on a file that has mixed tabs and spaces, first convert the tabs to spaces in a separate commit, then make your changes".

**Comment by jvasile** [comment]
+1

If you supply an editorconfig, I will use it.  I basically never touch tabs in emacs, so feel free to whisper hints to my editor behind my back.

**Comment by jvasile** [comment]
KFogel's PR #58 closes this.
