### ISSUE TITLE
Automate PSM deployment

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#7]
Write a script that allows us to deploy a new instance of the PSM automatically.  There's been some discussion of using [Fabric](http://www.fabfile.org/) for this.

Later, we'll likely put this in a cron job so that some of our public-facing instances can be destroyed and re-deployed nightly.

**Comment by cecilia-donnelly** [comment]
@jasonaowen mentioned that deploying to [Heroku](https://www.heroku.com/) may be the way to go for this.  More information to come once we have a reliable deployment process.

**Comment by cecilia-donnelly** [comment]
See https://github.com/OpenTechStrategies/psm/commit/9932648e15268da680ee60d0317d99af591000cf for more progress on automating deployment.

**Comment by cecilia-donnelly** [comment]
The deployment script @slifty added in 9932648 has now been shown to work on both RHEL 7.3 and CentOS 7.3.

**Comment by kfogel** [comment]
W00t!  Thanks (as per https://groups.google.com/d/msg/psm-dev/yYhr-Ikg5J8/aPackjGqBQAJ).

**Comment by cecilia-donnelly** [comment]
I'm going to close this.  We have a deploy script and continuous deployment running.  If we need something more specific later we can open a new issue.
