### ISSUE TITLE
Make Service Assurance Types less MN-specific

### ISSUE THREAD

**Issue by jvasile** [OpenTechStrategies/psm#88]
The service assurance stuff seems super specific to MN.  At some point we need to figure out whether that is generalizable structure or should be removed entirely.

**Comment by jasonaowen** [comment]
It appears that the assured services / Minnesota chemical dependency program feature was never completed. Migrating it to Hibernate 5 AND removing the MN-specificity AND getting it working when we don't even know if any other states have similar requirements seems like a lot of work; I think it will be better to re-implement if and when the time comes.

I've opened PR #239 to delete it. It will be in our history, and when the time comes I expect (hope!) we'll better understand how the various pieces of the system relate, and be better able to implement it in a state-agnostic way.
